Compatibility and Roadmap
cedardb/docs pull request #34
Opened 2024-10-10 12:22 UTC by ChrisWint

2024-10-10 13:49 UTC, pfent requested changes

2024-10-10 13:49 UTC, pfent commented on README.md
> +If you plan to use large tables, please create them using [TableGenerator](https://www.tablesgenerator.com/markdown_tables) and store the created table (File -> Save Table) in `unhosted_data/tables`
Also ich weis ja nicht. Die tgn files sind super hässlich und sollten wir finde ich nicht einchecken.
IntelliJ / CLion kann übrigens auch sehr gut Markdown Tabellen direkt editieren.

Ansonsten könnten wir uns überlegen die einfach als CSV zu speichern und mit nem Hugo shortcode zu HTML Tabellen zu machen:
https://randomgeekery.org/post/2020/06/csv-and-data-tables-in-hugo/

2024-10-10 13:49 UTC, pfent commented on content/compatibility/backend.md
> +title: Backend Compatibility
Dazu wir auch einen Punkt im Compatibility index schreiben.

2024-10-10 13:49 UTC, pfent commented on content/compatibility/backend.md
> +As CedarDB does not share PostgreSQL codebase and internal structures, some tables and views cannot have meaningful content and are only stubs to ensure tool compatibility. Catalog entries without me
```suggestion
As CedarDB does not share PostgreSQL codebase and internal structures, some tables and views cannot have meaningful content and are only exist for compatibility. Catalog entries without meaningful content are marked as such.
```

2024-10-10 13:49 UTC, pfent commented on content/compatibility/ecosystem_and_connectivity.md
> +As CedarDB does not share any codebase with PostgreSQL, however, not all features of PostgreSQL are available.
Da können wir dann auch auf `/clients/` linken

2024-10-10 13:49 UTC, pfent commented on content/compatibility/sql_features.md
> +| ON CONFLICT | Yes               | Only DO NOTHING                                                             |
tse. Das können wir doch seit zwei Tagen.

Muss ich nur noch docs für schreiben :see_no_evil:

2024-10-10 13:49 UTC, pfent commented on content/compatibility/sql_features.md
> +| User-Specified Aliases    |                   |                                                                                  |
? Das sollten wir doch können, oder?

2024-10-10 15:36 UTC, ChrisWint commented on content/compatibility/backend.md
> +title: Backend Compatibility
Meinst du auf der Compatibility landing page?
Die hab ich noch nicht umgeschrieben, das war aber der plan ja

2024-10-18 12:43 UTC, pfent approved these changes

2024-10-18 12:43 UTC, pfent commented on content/roadmap.md
> +| information_schema Support     | {{< iconinprogress >}} | [Documentation](/docs/compatibility/backend/)    |
Hier würde ich noch die Postgres system tables als done aufnehmen

2024-10-18 12:43 UTC, pfent commented on content/roadmap.md
> +| Vector Support               | {{< iconinprogress >}} | [Documentation](/docs/references/advanced/pgvector/)       |
range types

2024-10-18 14:12 UTC, MoritzS approved these changes

2024-10-18 14:13 UTC, merged