Add documentation for builtin functions
cedardb/docs pull request #7
Opened 2024-06-03 13:25 UTC by ChrisWint

Adds documentation for https://github.com/cedardb/cedardb/pull/131
To be merged after https://github.com/cedardb/cedardb/pull/131 was merged

2024-06-03 14:07 UTC, MoritzS requested changes

2024-06-03 14:07 UTC, MoritzS commented on content/references/sqlreference/functions/advanced_functions/_index.md
> +select * from cedar.kmeans(table(select * from (values(1,1),(2,2))t(x,y)), 1 order by x,y);
```suggestion
select * from cedar.kmeans(table (select id, title, year, length), 5 order by char_length(title), year, length);
```
Here, `table` is not a function, it's a keyword

2024-06-03 14:07 UTC, MoritzS commented on content/references/sqlreference/functions/advanced_functions/_index.md
> +The input can be a relation `table(movies)` or, as in the example above, the result of a subquery.
```suggestion
The input is a subquery or the name of a table whose values are used in the k-Means clustering.
The `table` keyword is necessary to tell the database system that the argument should be treated as a set of values instead of just a single value.
You can either write an entire subquery as in the example above or just use the name of an existing table, e.g., `cedar.kmeans(table (movies), ...)`.
```

2024-06-03 14:07 UTC, MoritzS commented on content/references/sqlreference/functions/advanced_functions/_index.md
> +CedarDB provides an optimized implementation to calculate the k-means for a set of tuples.
```suggestion
CedarDB provides an optimized implementation to cluster points with any number of dimensions using the k-Means clustering algorithm with an euclidean distance.
```

2024-06-03 14:07 UTC, MoritzS commented on content/references/sqlreference/functions/advanced_functions/_index.md
> +2. Arguments
```suggestion
The `cedar.kmeans` table function takes two arguments and an `order by` clause. The two arguments are the input and the number of clusters.
```

2024-06-03 14:07 UTC, MoritzS commented on content/references/sqlreference/functions/advanced_functions/_index.md
> +The second argument, specified after the `order by` keyword, denotes the columns which the k-means should use as dimensions.
```suggestion
The number of clusters must be a constant integer. It specifies the number of different clusters into which the k-Means algorithm will cluster the input. Generally, only low numbers of clusters (but more than one) will lead to meaningful results.

The `oder by` clause specifies which attributes the k-Means algorithm should use as dimensions. You need to specify this, since a table generally contains more data than just the dimension values. All expressions in the `oder by` clause are treated as double precision numbers.

The `cedar.kmeans` function returns an entire table, so you can only use it anywhere you could also write a subquery. The returned table contains all attributes and tuples of the input and one additional column with the name `cluster_id` which contains an integer between 0 and the specified number of clusters (exclusive). For each tuple the `cluster_id` attribute specifies the cluster the tuple was assigned to.
```

2024-06-03 14:07 UTC, MoritzS commented on content/references/sqlreference/functions/advanced_functions/_index.md
> +The `cedar.hash` function allows to calculate efficient 64bit hash values over an arbitrary amount of input arguments.
```suggestion
The `cedar.hash` function allows to calculate efficient 64-bit hash values over an arbitrary number of input arguments.
```

2024-06-03 14:07 UTC, MoritzS commented on content/references/sqlreference/functions/advanced_functions/_index.md
> +`cedar.split_part` allows to split text types by a separator string and accessing the result of the split by index.
```suggestion
`cedar.split_part` allows to split text types by a separator string and access the result of the split by index.
```

2024-06-03 14:07 UTC, MoritzS commented on content/references/sqlreference/functions/advanced_functions/_index.md
> +select cedar.split_part('abbcdbbef','bb',2);
```suggestion
select cedar.split_part('abbcdbbef', 'bb', 2);
```

2024-06-03 14:07 UTC, MoritzS commented on content/references/sqlreference/functions/advanced_functions/_index.md
> +### kmeans
```suggestion
### k-Means
```

2024-06-04 09:25 UTC, ChrisWint commented on content/references/sqlreference/functions/advanced_functions/_index.md
> +### kmeans
I want to keep this identical to the function name

2024-06-04 09:54 UTC, MoritzS approved these changes

2024-06-04 09:55 UTC, merged